services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://symfony:change-me@database:5432/symfony?serverVersion=15&charset=utf8"

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: change-me
      POSTGRES_DB: symfony
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app

  cypress:
    image: cypress/included:13.7.3
    working_dir: /e2e
    volumes:
      - ./frontend:/e2e
    environment:
      - CYPRESS_baseUrl=http://192.168.0.14:5173
    depends_on:
      - node
      - app
    profiles:
      - testing
    networks:
      - default

volumes:
  postgres_data: