services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://symfony:change-me@database:5432/symfony?serverVersion=15&charset=utf8"
    networks:
      - hr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: change-me
      POSTGRES_DB: symfony
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony"]
      interval: 10s
      timeout: 5s
      retries: 5

  node:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://app:8000/api
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - app
    networks:
      - hr-network

  cypress:
    image: cypress/included:13.7.3
    working_dir: /e2e
    volumes:
      - ./frontend:/e2e
    environment:
      - CYPRESS_baseUrl=http://node:5173
    depends_on:
      - node
      - app
    profiles:
      - testing
    networks:
      - hr-network

volumes:
  postgres_data:

networks:
  hr-network:
    driver: bridge