controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

employee_controllers:
  resource:
    path: ../src/Employee/Infrastructure/Controller/
    namespace: App\Employee\Infrastructure\Controller
  type: attribute
